### PR TITLE
SupportCustomLayout

### PR DESCRIPTION
**Pull request by Metalzoid**
Deleting =

- oas_rails_controller: layout false

Adding = 

- oas_rails_controller: 
- include Rails url_helpers for support route_path
- modify render html for include layout from configuration OAS_RAILS

- configuration.rb:
- attr_accessor :layout
- initialize @layout to false

- oas_rails_initializer :
- # config.layout = "application" + documentation

It's works fine for me

### CODE REVIEW

**Comment by a-chacon** [comment]
hey @Metalzoid the code looks good. But I was thinking if you add a layout to the page maybe you will be duplicating code like the html, head, body tags. You will be creating a html page inside another html at least you overwrite the index page too. 

I mean, the index page already have this structure:

```
<!DOCTYPE html>
<html>
  <head>
    <title><%= OasRails.config.info.title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <!-- Important: rapi-doc uses utf8 characters -->
    <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
  </head>
  <body>
    
  </body>
</html>
```

Is it ok? So maybe the feature can include a modification in the index view too.

And which is the use case you want to cover here? I mean, Why you need this feature?

**Comment by Metalzoid** [comment]
I see ! I need this feature for adding my custom navbar =)

and if we specify adding this lines in the custom layouts user in the <head> : 
```html
    <meta charset="utf-8">
    <!-- Important: rapi-doc uses utf8 characters -->
    <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
``` 

It's good for you ?

**Comment by a-chacon** [comment]
mm I think, we can use by default the layout of the engine. Move all the code to it, and in the index view let something like this:
```
    <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
    <rapi-doc
      spec-url = "<%= OasRails::Engine.routes.find_script_name({}) %>.json"
      theme = "dark"
      bg-color="#0F172A"
      text-color= "#f7f7f7"
      show-header = 'false'
      primary-color = "#2de410"
      font-size="largest"
      show-method-in-nav-bar="as-colored-text"
      nav-text-color="#f7f7f7"
      nav-item-spacing="relaxed"
      allow-spec-file-download="true"
      >
    </rapi-doc>
```

Then you can replace the engine layout with your layout with the code you defined. Can you understand me? Just leave in the index.html.erb file the things for making the rapidoc works. It should not depend on the client layout because it will be easy to forget.

**Comment by Metalzoid** [comment]
And the charset UTF8??

**Comment by a-chacon** [comment]
mm good question about the utf-8. It should not depend on the user too. Do you have any idea? I will think about it.

**Comment by Metalzoid** [comment]
Since this is code intended for developers, I don't think it will be a problem. At worst, in the docs, in the "use your own layouts" section, specify to use UTF8 in case of character display problems?

**Comment by a-chacon** [comment]
ok, you are right. So it may be finished. I will review and merge it at the end of the day. Thank you!

**Review by a-chacon — APPROVED** [review]

**Pull request merged**
